name: dl-challenge
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pytorch=2.1.0
  - torchvision=0.10.0
  - pip
  - scikit-image
  - scikit-learn
  - jupyterlab
  - tqdm>=4.36
  - pip:
      - onnxruntime
